name: 'logistics_demo'
version: '1.0'
profile: 'logistics_demo'

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  logistics_demo:
    bronze:
      schema: bronze
      alias: "{{ this.name }}"
      materialized: view
    silver:
      schema: silver
      alias: "{{ this.name }}"
      materialized: table
    gold:
      schema: gold
      alias: "{{ this.name }}"
      materialized: table
