name: 'logistics_demo'
version: '1.0'
profile: 'logistics_demo'

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

models:
  logistics_demo:
    bronze:
      schema: "{{ generate_schema_name('bronze', this) }}"
      alias: "{{ generate_alias_name(this.name, this) }}"
      materialized: view
    silver:
      schema: "{{ generate_schema_name('silver', this) }}"
      alias: "{{ generate_alias_name(this.name, this) }}"
      materialized: table
    gold:
      schema: "{{ generate_schema_name('gold', this) }}"
      alias: "{{ generate_alias_name(this.name, this) }}"
      materialized: table
