name: Medallion ELT (Bronze→Silver→Gold)

on:
  workflow_call:
    inputs:
      environment:
        description: "Target environment (dev/prod/ci)"
        required: false
        type: string
      extra_flags:
        description: "Optional flags or selectors"
        required: false
        type: string
      requirements_path:
        description: "Path to Python requirements file"
        required: false
        type: string
    secrets:
      SNOWFLAKE_ACCOUNT: {required: false}
      SNOWFLAKE_USER: {required: false}
      SNOWFLAKE_PASSWORD: {required: false}
      SNOWFLAKE_ROLE: {required: false}
      SNOWFLAKE_WAREHOUSE: {required: false}
      SLACK_WEBHOOK_URL: {required: false}

concurrency:
  group: elt-${{ github.ref }}
  cancel-in-progress: false

env:
  # Snowflake / dbt
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  # Slack (optional)
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dbt_env: ${{ steps.set-env.outputs.DBT_ENVIRONMENT }}
      dbt_schema: ${{ steps.set-env.outputs.DBT_TARGET_SCHEMA }}
    env:
      DBT_PROFILES_DIR: scripts/dbt
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11 (with pip cache)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            **/requirements.txt
            ${{ inputs.requirements_path }}

      - name: Install Python dependencies
        if: inputs.requirements_path != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r "${{ inputs.requirements_path }}"

      - name: Ensure profiles.yml exists
        run: test -f scripts/dbt/profiles.yml

      - name: Determine dbt target (env/schema)
        id: set-env
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "DBT_TARGET_SCHEMA=prod" >> $GITHUB_ENV
            echo "DBT_ENVIRONMENT=prod" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "DBT_TARGET_SCHEMA=dev" >> $GITHUB_ENV
            echo "DBT_ENVIRONMENT=dev" >> $GITHUB_ENV
          else
            ISSUE_ID=${{ github.run_id }} # isolated CI schema by run
            echo "DBT_TARGET_SCHEMA=ci_${ISSUE_ID}" >> $GITHUB_ENV
            echo "DBT_ENVIRONMENT=ci_cd" >> $GITHUB_ENV
          fi
          echo "DBT_TARGET_SCHEMA=${DBT_TARGET_SCHEMA}" >> $GITHUB_OUTPUT
          echo "DBT_ENVIRONMENT=${DBT_ENVIRONMENT}" >> $GITHUB_OUTPUT

      - name: dbt deps
        working-directory: scripts/dbt
        run: dbt deps

  # ===== E (Extract) + L (Load) → Bronze =====
  bronze_extract_load:
    needs: setup
    runs-on: ubuntu-latest
    env:
      DBT_ENVIRONMENT: ${{ needs.setup.outputs.dbt_env }}
      DBT_TARGET_SCHEMA: ${{ needs.setup.outputs.dbt_schema }}
      DBT_PROFILES_DIR: scripts/dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ${{ inputs.requirements_path }}

      - name: Install ELT dependencies
        if: inputs.requirements_path != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r "${{ inputs.requirements_path }}"

      - name: Ensure profiles.yml exists
        run: test -f scripts/dbt/profiles.yml

      # Option A (demo): use seeds as extract artifacts into Bronze
      - name: Extract from sources (demo via dynamic seeds)
        run: |
          # If you have a real extractor, swap this for: python scripts/python/extract_sources.py
          python scripts/python/create_seed.py

      - name: Load Bronze (seed/external→tables)
        working-directory: scripts/dbt
        run: |
          dbt seed
          dbt run --select path:models/bronze/

      - name: Bronze basic checks (schema & rowcount smoke)
        working-directory: scripts/dbt
        run: dbt test --select tag:bronze,tag:smoke+

  # ===== T (Transform) → Silver =====
  silver_transform:
    needs: bronze_extract_load
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.silver_tests.outputs.passed }}
      total: ${{ steps.silver_tests.outputs.total }}
      rate: ${{ steps.silver_tests.outputs.rate }}
    env:
      DBT_PROFILES_DIR: scripts/dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ${{ inputs.requirements_path }}

      - name: Install dbt deps
        if: inputs.requirements_path != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r "${{ inputs.requirements_path }}"

      - name: Build Silver (cleaned/conformed)
        working-directory: scripts/dbt
        run: dbt run --select path:models/silver/

      - name: Silver tests (constraints, nullability, referential)
        id: silver_tests
        working-directory: scripts/dbt
        run: |
          dbt test --select path:models/silver/ --output json > ../silver_test_results.json || true
          PASSED=$(jq '[.results[] | select(.status=="pass")] | length' ../silver_test_results.json)
          TOTAL=$(jq '.results | length' ../silver_test_results.json)
          RATE=$(python - <<'PY'
          import json; d=json.load(open("silver_test_results.json"))
          tot=len(d.get("results",[])) or 1
          pas=sum(1 for r in d.get("results",[]) if r.get("status")=="pass")
          print(round(100*pas/tot,1))
          PY
          )
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "rate=$RATE" >> $GITHUB_OUTPUT

      - name: Silver source freshness
        id: silver_fresh
        working-directory: scripts/dbt
        run: |
          dbt source freshness --output json > ../silver_fresh.json || true
          echo "file=../silver_fresh.json" >> $GITHUB_OUTPUT

  # ===== T (Transform) → Gold =====
  gold_transform:
    needs: silver_transform
    runs-on: ubuntu-latest
    outputs:
      passed: ${{ steps.gold_tests.outputs.passed }}
      total: ${{ steps.gold_tests.outputs.total }}
      rate: ${{ steps.gold_tests.outputs.rate }}
    env:
      DBT_PROFILES_DIR: scripts/dbt
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: ${{ inputs.requirements_path }}

      - name: Install dbt deps
        if: inputs.requirements_path != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r "${{ inputs.requirements_path }}"

      - name: Build Gold (business marts)
        working-directory: scripts/dbt
        run: dbt run --select path:models/gold/

      - name: Gold tests (business rules)
        id: gold_tests
        working-directory: scripts/dbt
        run: |
          dbt test --select path:models/gold/ --output json > ../gold_test_results.json || true
          PASSED=$(jq '[.results[] | select(.status=="pass")] | length' ../gold_test_results.json)
          TOTAL=$(jq '.results | length' ../gold_test_results.json)
          RATE=$(python - <<'PY'
          import json; d=json.load(open("gold_test_results.json"))
          tot=len(d.get("results",[])) or 1
          pas=sum(1 for r in d.get("results",[]) if r.get("status")=="pass")
          print(round(100*pas/tot,1))
          PY
          )
          echo "passed=$PASSED" >> $GITHUB_OUTPUT
          echo "total=$TOTAL" >> $GITHUB_OUTPUT
          echo "rate=$RATE" >> $GITHUB_OUTPUT

  # ===== ELT Health Notification (Slack) =====
  notify:
    needs: [silver_transform, gold_transform]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Summarize ELT outcome
        id: sum
        run: |
          echo "silver_passed=${{ needs.silver_transform.outputs.passed || '0' }}" >> $GITHUB_OUTPUT
          echo "silver_total=${{ needs.silver_transform.outputs.total  || '0' }}" >> $GITHUB_OUTPUT
          echo "silver_rate=${{ needs.silver_transform.outputs.rate   || '0' }}" >> $GITHUB_OUTPUT
          echo "gold_passed=${{ needs.gold_transform.outputs.passed   || '0' }}" >> $GITHUB_OUTPUT
          echo "gold_total=${{ needs.gold_transform.outputs.total     || '0' }}" >> $GITHUB_OUTPUT
          echo "gold_rate=${{ needs.gold_transform.outputs.rate       || '0' }}" >> $GITHUB_OUTPUT
          echo "status=${{ (needs.silver_transform.result == 'success' && needs.gold_transform.result == 'success') && 'OK' || 'FAIL' }}" >> $GITHUB_OUTPUT

      - name: Slack — ELT Status
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                { "type":"header", "text": { "type":"plain_text", "text":"${{ steps.sum.outputs.status == 'OK' && '✅ Medallion ELT Success' || '🚨 Medallion ELT Failure' }}" } },
                { "type":"section", "fields": [
                  { "type":"mrkdwn", "text":"*Branch:* `${{ github.ref_name }}`" },
                  { "type":"mrkdwn", "text":"*Run:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.run_id }}>" }
                ]},
                { "type":"divider" },
                { "type":"section", "text": { "type":"mrkdwn",
                  "text":"*Silver (conformed)*\n• Tests: *${{ steps.sum.outputs.silver_passed }} / ${{
                    steps.sum.outputs.silver_total }}* (*${{ steps.sum.outputs.silver_rate }}%*)" } },
                { "type":"section", "text": { "type":"mrkdwn",
                  "text":"*Gold (business marts)*\n• Tests: *${{ steps.sum.outputs.gold_passed }} / ${{
                    steps.sum.outputs.gold_total }}* (*${{ steps.sum.outputs.gold_rate }}%*)" } },
                { "type":"context", "elements":[
                  { "type":"mrkdwn", "text":"Layers executed: *Bronze → Silver → Gold*. Freshness checks run at Silver." }
                ]}
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
