CREATE OR REPLACE TABLE LOGISTICS_DEMO.{{SCHEMA_NAME}}.inventory_movements (
    MOVEMENT_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20),
    WAREHOUSE_ID VARCHAR(20),
    MOVEMENT_DATE DATE,
    QUANTITY INTEGER,
    MOVEMENT_TYPE VARCHAR(20)
);

CREATE OR REPLACE TABLE LOGISTICS_DEMO.{{SCHEMA_NAME}}.customer_orders (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20),
    WAREHOUSE_ID VARCHAR(20),
    ORDER_DATE DATE,
    QUANTITY INTEGER,
    SALES_CHANNEL VARCHAR(20)
);
