--
-- Create base tables in the dynamic schema.  These tables mirror
-- the structure of the CSV seeds generated by `create_seed.py`.
-- The {{SCHEMA_NAME}} token will be replaced by the provisioning
-- script to build tables in a feature‑specific schema (e.g. for
-- issue-driven runs).  If these tables already exist, they are
-- replaced.  Note: the actual data is loaded via dbt seeds.
CREATE OR REPLACE TABLE LOGISTICS_DEMO.{{SCHEMA_NAME}}.inventory_movements (
    MOVEMENT_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20),
    WAREHOUSE_ID VARCHAR(20),
    MOVEMENT_DATE DATE,
    QUANTITY INTEGER,
    MOVEMENT_TYPE VARCHAR(20)
);

CREATE OR REPLACE TABLE LOGISTICS_DEMO.{{SCHEMA_NAME}}.customer_orders (
    ORDER_ID VARCHAR(20) PRIMARY KEY,
    PRODUCT_ID VARCHAR(20),
    WAREHOUSE_ID VARCHAR(20),
    ORDER_DATE DATE,
    QUANTITY INTEGER,
    SALES_CHANNEL VARCHAR(20)
);
