SELECT
    REPORT_DATE,
    WAREHOUSE_NAME,
    PRODUCT_NAME,
    TOTAL_ORDERS,
    TOTAL_UNITS_SHIPPED,
    TOTAL_UNITS_REPLENISHED,
    STOCK_TURNOVER_RATIO
FROM LOGISTICS_DEMO.{{SCHEMA_NAME}}.DAILY_INVENTORY_KPIS
ORDER BY REPORT_DATE DESC
LIMIT 10