GRANT USAGE ON SCHEMA LOGISTICS_DEMO.{{SCHEMA_NAME}} TO ROLE LOGISTICS_DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA LOGISTICS_DEMO.{{SCHEMA_NAME}} TO ROLE LOGISTICS_DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA LOGISTICS_DEMO.{{SCHEMA_NAME}} TO ROLE LOGISTICS_DBT_ROLE;