CREATE OR REPLACE WAREHOUSE ANALYTICS_WH 
    WAREHOUSE_SIZE = 'XSMALL' 
    AUTO_SUSPEND = 300 
    AUTO_RESUME = TRUE
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 1
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for our demo lab.';
CREATE DATABASE IF NOT EXISTS LOGISTICS_DEMO COMMENT = 'Database for DataOps Course';
CREATE ROLE IF NOT EXISTS DATA_ANALYST COMMENT = 'Role for data analysts to view and query data.';
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE DATA_ANALYST;
GRANT OPERATE ON WAREHOUSE ANALYTICS_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE LOGISTICS_DEMO TO ROLE DATA_ANALYST;
GRANT CREATE SCHEMA ON DATABASE LOGISTICS_DEMO TO ROLE DATA_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE LOGISTICS_DEMO TO ROLE DATA_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE LOGISTICS_DEMO TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA LOGISTICS_DEMO.PUBLIC TO ROLE DATA_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA LOGISTICS_DEMO.PUBLIC TO ROLE DATA_ANALYST;  
CREATE USER IF NOT EXISTS runink PASSWORD='SecurePassword123' DEFAULT_WAREHOUSE='ANALYTICS_WH' DEFAULT_ROLE='DATA_ANALYST';
